Web-C#-asp.net-all/YOUTUBE/YOUTUBE/Controllers/LastVideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YOUTUBE.Models;
namespace YOUTUBE.Controllers
{
    [Authorize(Roles = "phanquyen")]
    public class LastVideoController : Controller
    {

        DataClasses1DataContext db = new DataClasses1DataContext();
        public ActionResult Index()
        {
            return View();
        }
        // GET: LastVideo
        [HttpPost]
        public ActionResult Index(lastvideo cv)
        {
            if (Session["acc"]!=null)
            {
                int matk = Convert.ToInt32(Session["acc"]);
                int mavideo = Convert.ToInt32(Request.Form["mavideo"]);
                lastvideo lv = db.lastvideos.Where(x => x.matk == matk && x.mavideo == mavideo).SingleOrDefault();
                if(lv ==null)
                {
                    db.luuvideoxemsau(matk, mavideo);

                    return RedirectToAction("Detail", "VIDEO");
                }else if(lv!=null)
                {
                    TempData["daluu"] = "Video đã lưu";
                    return RedirectToAction("Detail", "VIDEO");
                }
              
            }
            else
            {
                return RedirectToAction("logins", "Account");
            }
         return View();
        }
        public ActionResult showlastvideo()
        {
            if (Session["acc"]!=null)
            {
                int idacc = Convert.ToInt32(Session["acc"]);
                List<lastvideo> ls = db.lastvideos.ToList();
                List<video> vi = db.videos.ToList();
                List<account> a = db.accounts.ToList();
                var innerjoin = (from lastv in ls
                                 join v in vi on lastv.mavideo equals v.Mavideo into table1
                                 from v in table1.DefaultIfEmpty()
                                 join ac in a on v.matk equals ac.matk
                                 where lastv.matk == idacc
                                 select new innerjoin
                                 {
                                     videoo=v,accountt=ac,lastvideos=lastv
                                 }).ToList();
            return View(innerjoin);
            }else
            {
                return RedirectToAction("logins", "Account");
            }
           
        }
    }
}

Web-C#-asp.net-all/YOUTUBE/YOUTUBE/Controllers/VIDEOController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
//using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YOUTUBE.Models;
namespace YOUTUBE.Controllers
{

    [Authorize(Roles = "phanquyen")]
    public class VIDEOController : Controller
    {
        DataClasses1DataContext db = new DataClasses1DataContext();
        // GET: VIDEO
       
        public ActionResult Detail(int ?mv,int ?id)
        {
            if (Session["acc"] != null)
            {
                if (mv != null && id != 0)
                {
                    Session["mv"] = mv;
                    Session["id"] = id;
                }

                List<video> v = db.videos.ToList();
                List<account> a = db.accounts.ToList();
                List<User> u = db.Users.ToList();
                //video vi;
                //account ac;
                //User us;
                var quey = (from vi in v
                            join ac in a on vi.matk equals ac.matk into table1
                            from ac in table1.DefaultIfEmpty()
                            join uu in u on ac.matk equals uu.matk
                            where vi.Mavideo == Convert.ToInt32(Session["mv"])
                            select new innerjoin { videoo = vi, accountt = ac, user = uu }).SingleOrDefault();
                var quey2 = from vi in v
                            join ac in a on vi.matk equals ac.matk into table1
                            from ac in table1.DefaultIfEmpty()
                            join uu in u on ac.matk equals uu.matk
                            where vi.categoryid == Convert.ToInt32(Session["id"])
                            select new innerjoin { videoo = vi, accountt = ac, user = uu };


                Session["filevideo"] = quey.videoo.filevideo;
                Session["mavideo"] = quey.videoo.Mavideo;
                Session["iduser"] = quey.accountt.matk;
                int idacc = Convert.ToInt32(Session["acc"]);
                dangkykenh c = db.dangkykenhs.Where(x => x.matk == quey.accountt.matk && x.matkuser == idacc).SingleOrDefault();
                channel c2 = db.channels.Where(x => x.matk == quey.accountt.matk).SingleOrDefault();
                if (c2 == null && c == null)
                {
                    Session["dangky"] = null;
                    Session["dadangky"] = null;
                    Session["kenhchuatao"] = "ok";
                }
                else if (c2 != null && c == null)
                {
                    Session["kenhchuatao"] = null;
                    Session["makenh"] = c2.MaDK;
                    Session["dangky"] = c2.MaDK;
                    Session["dadangky"] = null;
                }


                if (c2 != null && c != null)
                {
                    Session["kenhchuatao"] = null;
                    Session["dangky"] = null;
                    Session["dadangky"] = c2.MaDK;


                }


                Session["namevideo"] = quey.videoo.nametitle;
                Session["noidung"] = quey.videoo.noidung;
                Session["imageuser"] = quey.user.imageuser;
                Session["nameuser"] = quey.accountt.username;
                int mavideo = Convert.ToInt32(Session["mavideo"]);
                List<User> us = db.Users.ToList();
                List<comment> comments = db.comments.ToList();
                List<video> ve = db.videos.ToList();
                var quey3 = from use in us
                            join co in comments on use.matk equals co.matk
                            where co.mavideo == mavideo
                            select new innerjoin { commentt = co, user = use };
                TempData["binhluan"] = quey3.ToList();
                int account = Convert.ToInt32(Session["acc"]);
                List<User> uss = db.Users.ToList();
                List<dangkykenh> ch = db.dangkykenhs.ToList();
                List<account> accc = db.accounts.ToList();
                var quy = from use in uss
                          join ace in accc on use.matk equals ace.matk into table1
                          from ace in table1.DefaultIfEmpty()
                          join chh in ch on ace.matk equals chh.matk
                          where chh.matkuser == account
                          select new innerjoin { dk = chh, user = use, accountt = ace };
                Session["dskenhdy"] = quy.ToList();
                return View(quey2);
            }else
            {
                return RedirectToAction("logins", "Account");
            }
                
        }

        public ActionResult LOADVIDEO()
        {
            //if (Session["acc"]!=null)
            //{
                List<video> v = db.videos.ToList();
                List<User> us = db.Users.ToList();
                List<account> ac = db.accounts.ToList();
                var quy = from vi in v
                          join ace in ac on vi.matk equals ace.matk into table1
                          from ace in table1.DefaultIfEmpty()
                          join user in us on ace.matk equals user.matk
                          select new innerjoin { videoo = vi, user = user, accountt = ace };
            int idacc = Convert.ToInt32(Session["acc"]);
            List<thongbao> tb = db.thongbaos.ToList();
            List<account> accout = db.accounts.ToList();
            List<User> u = db.Users.ToList();
            List<dangkykenh> dk = db.dangkykenhs.ToList(); 
            var innerjoin = (from thog in tb
                             join acc in accout on thog.matk equals acc.matk into table1
                             from acc in table1.DefaultIfEmpty()
                             join user in u on acc.matk equals user.matk into table2
                             from user in table2.DefaultIfEmpty()
                             join dangkyk in dk on user.matk equals dangkyk.matk
                             where dangkyk.matkuser==idacc
                             select new innerjoin { dangkykenhs=dangkyk,accountt = acc, thongbaos = thog, user = user }).ToList();
            Session["thongbao"] = innerjoin;
            List<danhmuc> dm = db.danhmucs.ToList();
            Session["danhmuc"] = dm;
            return View(quy);
            //}else
            //{
            //    return RedirectToAction("logins", "Account");
            //}
         
        }

        [Authorize(Roles = "phanquyen")]
        public ActionResult create()
        {
            List<danhmuc> dm = db.danhmucs.ToList();
            TempData["danhmuc"]=dm;
            int id = Convert.ToInt32(Session["acc"]);
            List<account> accounts = db.accounts.ToList();
            List<video> videos = db.videos.Where(x=>x.matk==id).ToList();
            var innerjoin = (from vi in videos
                             join a in accounts on vi.matk equals a.matk
                             where a.matk == id
                             select new innerjoin { accountt = a, videoo = vi }).ToList();
            Session["danhsachvideocuaban"]=innerjoin;
            return View();
        }
        [HttpPost]
        public ActionResult create(video v, HttpPostedFileBase imgfile, HttpPostedFileBase imgfile2)
        {
            
            v.filevideo = uploadvideo(imgfile);
            v.imagetitle = uploadImage(imgfile2);
            v.matk =Convert.ToInt32(Request.Form["matk"]);
            v.categoryid = Convert.ToInt32(Request.Form["MaDM"]);
            db.createvideo(v.filevideo, v.imagetitle, v.nametitle, v.categoryid, v.noidung, v.matk);
            thongbao tb= new thongbao();
            tb.noidung = "Vừa có video mới click để xem";
            tb.matk = v.matk;
            db.thongbaouser(tb.matk,tb.noidung);
            ViewBag.Message = "Them thanh cong video";
            List<danhmuc> dm = db.danhmucs.ToList();
            TempData["danhmuc"] = dm;
            return View();
        }
        public string uploadvideo(HttpPostedFileBase imgfile)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();

            if (imgfile != null && imgfile.ContentLength > 0)
            {
                string extension = Path.GetExtension(imgfile.FileName);
                //if (extension.ToLower().Equals(".jgp") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                //{
                    try
                    {
                        path = Path.Combine(Server.MapPath("/Content/video/"), random + Path.GetFileName(imgfile.FileName));
                        imgfile.SaveAs(path);
                        path = "/Content/video/" + random + Path.GetFileName(imgfile.FileName);





                        //var stream = new FileStream(path, FileMode.Create);
                        //stream.CopyTo(imgfile.InputStream);



                    }
                    catch (Exception ex)
                    {
                        path = "-1";
                    }

                //}
                //else
                //{
                //    Response.Write("<script>alert('only jpg,png,jpeg' )</script>");
                //}
            }
            else
            {
                Response.Write("<script>alert('please select a file' )</script>");
                path = "-1";
            }


            return path;
        }
        public string uploadImage(HttpPostedFileBase imgfile2)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();

            if (imgfile2 != null && imgfile2.ContentLength > 0)
            {
                string extension = Path.GetExtension(imgfile2.FileName);

Web-C#-asp.net-all/YOUTUBE/YOUTUBE/Views/VIDEO/Detail.cshtml
@model IEnumerable<YOUTUBE.Models.innerjoin>

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}


    
    @*@foreach(var item in Model) {*@ 
    <div class="container play-container">
        <div class="row">
            <div class="play-video">
                <video controls autoplay>
                    <source src="@Session["filevideo"]" type="video/mp4">
                </video>

                <div class="tags">
                    
                </div>
                <h3>@Session["namevideo"]</h3>
                <div class="play-video-info">
                    @using (Html.BeginForm("Index", "LastVideo",FormMethod.Post))
                    {
                        <div>
                            <input hidden name="mavideo" value="@Session["mavideo"]" />
                            <button type="submit"><img src="/Content/img/save.png" /> Save </button>

                        </div>

                    }
                <label style="color:red;">@TempData["daluu"]</label>


                </div>
                <hr>
                <div class="publisher">
                    <img src="@Session["imageuser"]">
                    <div>
                        <p>@Session["nameuser"]</p>
                        <span>10.252 Người đăng kí</span>
                    </div>
                    <form action="/Channel/dangkykenh" method="post">
                        <input hidden name="makenh" type="text" value="@Session["makenh"]" />
                        <input hidden name="matk" type="text" value="@Session["iduser"]" />
                        <input hidden name="matkuser" type="text" value="@Session["acc"]" />
                        @if (Session["dangky"] != null)
                        {
                            <button type="submit">Đăng kí</button>
                        }
                        @if (Session["kenhchuatao"] != null)
                        {
                            <label style="color:red;">Kênh chưa được tạo</label>
                        }
                        @if(Session["dadangky"]!=null)
                        {
                         <button disabled type="submit" style="background-color:gray"> Đã đăng kí</button>
                            }
                    </form>
                    <label style="color:red;">@ViewBag.Message</label>
                </div>

                <div class="vid-description">
                    <p></p>

                    <hr>
                    <form action="/binhLuan/Index" method="post">
                        <div class="add-comment">
                            <img src="@Session["imageusers"]">
                            <input type="text" name="noidung" placeholder="Thêm bình luận của bạn vào đây...">
                            <input type="submit" />
                        </div>
                    </form>

                    @foreach (var it in TempData["binhluan"] as List<YOUTUBE.Models.innerjoin>)
                    {
                        <div class="old-comment">
                            <img src="@it.user.imageuser">
                            <div>

                                <p>@it.commentt.noidung</p>

                            </div>
                        </div>
                    }




                </div>





            </div>
            @*}*@
            <div class="right-sidebar">


                @foreach (var item2 in Model)
                {
                    <div class="side-video-list">
                        <a href="" class="small-thumbnail"><img src="@item2.videoo.imagetitle"></a>
                        <div class="vid-info">
                            <a href=""> @item2.videoo.nametitle</a>
                            <p>@item2.accountt.username</p>
                            <p>15k lượt xem</p>
                        </div>
                    </div>
                }








            </div>
        </div>

    </div>

Web-C#-asp.net-all/YOUTUBE/YOUTUBE/Views/VIDEO/Detail2.cshtml
@{
    ViewBag.Title = "Detail2";
    Layout =null;
}
<div class="right-sidebar">


    @foreach (var item in Model)
    {
        <div class="side-video-list">
            <a href="" class="small-thumbnail"><img src="@item.videoo.imagetitle"></a>
            <div class="vid-info">
                <a href=""> @item.videoo.nametitle</a>
                <p>@item.accountt.username</p>
                <p>15k lượt xem</p>
            </div>
        </div>
    }








</div>

Web-C#-asp.net-all/YOUTUBE/YOUTUBE/Views/VIDEO/Edit.cshtml
@model YOUTUBE.Models.video

@{
    ViewBag.Title = "create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<style>
    input#imgfile {
        margin: 24px;
        border: 1px solid;
        background-color: green;
        color: white;
    }

    input#nametitle {
        margin: 24px;
        width: 250px;
        height: 100px;
    }

    input#noidung {
        margin: 24px;
        width: 250px;
        height: 100px;
    }

    input.btn.btn-default {
        margin: 24px;
        width: 300px;
        height: 50px;
        background-color: green;
        color: white;
        font-size: 30px;
    }

    form {
        display: flex;
        justify-content: center;
    }

    select#MaDM {
        margin: 24px;
        width: 250px;
        height: 40px;
    }

    video#showimg {
        margin-left: -300px;
        background-color: black;
        margin-bottom: 30px;
        margin-top: 30px;
    }
</style>
<h2>Thêm Video mới</h2>

@using (@Html.BeginForm("Edit", "VIDEO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Mavideo)

        <div class="form-group">
            <h3>Chọn file video</h3>
            <div class="form-group">
                <label for="pwd">filevideo</label>

                <input type="file" class="form-control btn btn-info" id="file" name="imgfile" onchange="display(event)" />
                <video src="@Model.filevideo" id="showimg" autoplay style="width: 200px;height: 200px;">
            </div>

        </div>

        <div class="form-group">
            <h3>Hình ảnh video</h3>
            <div id="selectedBanner">
                <img src="@Model.imagetitle" id="showimg2" style="width: 200px;height: 200px;">
            </div>
            <div class="form-group">
                <label for="pwd">filevideo</label>
                <input type="file" class="form-control btn btn-info" id="imgfile" name="imgfile2" onchange="display(event2)" />
                @*<img src="" id="showimg2"  style="width: 200px;height: 200px;">*@
            </div>
        </div>

        <div class="form-group">
            <h3>Tên video</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nametitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nametitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h3>Danh mục</h3>
            <div class="col-md-10">
                <select name="MaDM">
                    @foreach (var it in TempData["danhmuc"] as List<YOUTUBE.Models.danhmuc>)
                    {
                        <option value="@it.MaDM">@it.tendm</option>
                    }

                </select>
            </div>
        </div>

        <div class="form-group">
            <h3>Nội dung</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.noidung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noidung, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<input type="text" name="matk" value="@Session["acc"]" hidden />*@
        <div hidden class="form-group">
            <h3>Nội dung</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.matk, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.matk, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (ViewBag.Message != null)
{
    <script>
    alert("@ViewBag.Message");
    </script>
}
<style>
    .video {
        align-items: center;
    }
</style>

<script>
    function display(event) {
        document.getElementById("showimg").src = URL.createObjectURL(event.target.files[0]);
    }
    //function display(event2) {
    //    document.getElementById("showimg2").src = URL.createObjectURL(event2.target.files[0]);
    //}
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script>
    var selDiv = "";
    var storedFiles = [];
    $(document).ready(function () {
        $("#imgfile").on("change", handleFileSelect);
        selDiv = $("#selectedBanner");
    });

    function handleFileSelect(e) {
        var files = e.target.files;
        var filesArr = Array.prototype.slice.call(files);
        filesArr.forEach(function (f) {
            if (!f.type.match("image.*")) {
                return;
            }
            storedFiles.push(f);

            var reader = new FileReader();
            reader.onload = function (e) {
                var html =
                    '<img src="' +
                    e.target.result +
                    "\" data-file='" +
                    f.name +
                    "alt='Category Image' height='200px' width='200px'>";
                selDiv.html(html);
            };
            reader.readAsDataURL(f);
        });
    }
</script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web-C#-asp.net-all/YOUTUBE/YOUTUBE/Views/VIDEO/LOADVIDEO.cshtml
@model IEnumerable<YOUTUBE.Models.innerjoin>

@{
    ViewBag.Title = "LOADVIDEO";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<div class="banners">
    <style>
        .category {
            margin: 20px;
            display: flex;
            align-items: center;
        }
        .btn-category {
            width: 100px;
            height: 50px;
            border-radius: 7%;
        }
        .btn-category:hover{
            background-color:gray;
        }
        .img-title{
            height:200px;
            border:1px solid black;
        }
    </style>
    <div class="category">
        <label>Danh mục:</label>
       
        @foreach (var it in Session["danhmuc"] as List<YOUTUBE.Models.danhmuc>)
    {
    using (@Html.BeginForm("timkiemtheodanhmuc", "DanhMuc", FormMethod.Post))
    {
        <input name="iddm" value="@it.MaDM" hidden />
        <button class="btn-category">@it.tendm</button>
    }

    }

</div>
    <img class="img-title" src="/Content/img/baocao.png">
</div>
<div class="list-container">
    @foreach (var item in Model)
    {
       
        <div class="vid-list">
            <a href="/VIDEO/Detail?mv=@item.videoo.Mavideo&id=@item.videoo.categoryid"><img src="@item.videoo.imagetitle" class="thumbnail"></a>
            <div class="flex-div">
                <img src="@item.user.imageuser">
                <div class="vid-info">
                    <a href="play-video.html">@item.videoo.nametitle</a>
                    <p>@item.accountt.username</p>
                    <p>15k lượt xem &bull; 8 ngày trước</p>
                </div>
            </div>
        </div>
    }
</div>

Web-C#-asp.net-all/YOUTUBE/YOUTUBE/Views/VIDEO/create.cshtml
@model YOUTUBE.Models.video

@{
    ViewBag.Title = "create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<style>
    input#imgfile {
        margin: 24px;
        border: 1px solid;
        background-color: green;
        color: white;
    }

    input#nametitle {
        margin: 24px;
        width: 250px;
        height: 100px;
    }

    input#noidung {
        margin: 24px;
        width: 250px;
        height: 100px;
    }

    input.btn.btn-default {
        margin: 24px;
        width: 300px;
        height: 50px;
        background-color: green;
        color: white;
        font-size: 30px;
    }

    form {
        display: flex;
        justify-content: center;
    }

    select#MaDM {
        margin: 24px;
        width: 250px;
        height: 40px;
    }

    video#showimg {
        margin-left: -300px;
        background-color: black;
        margin-bottom: 30px;
        margin-top: 30px;
    }
</style>
<h2>Thêm Video mới</h2>

@using (@Html.BeginForm("create", "VIDEO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <h3>Chọn file video</h3>
            <div class="form-group">
                <label for="pwd">filevideo</label>

                <input type="file" class="form-control btn btn-info" id="file" name="imgfile" onchange="display(event)" />
                <video src="" id="showimg" autoplay style="width: 200px;height: 200px;">
            </div>

        </div>

        <div class="form-group">
            <h3>Hình ảnh video</h3>
            <div id="selectedBanner"></div>
            <div class="form-group">
                <label for="pwd">filevideo</label>
                <input type="file" class="form-control btn btn-info" id="imgfile" name="imgfile2" onchange="display(event2)" />
                @*<img src="" id="showimg2"  style="width: 200px;height: 200px;">*@
            </div>
        </div>

        <div class="form-group">
            <h3>Tên video</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nametitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nametitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h3>Danh mục</h3>
            <div class="col-md-10">
                <select name="MaDM">
                    @foreach (var it in TempData["danhmuc"] as List<YOUTUBE.Models.danhmuc>)
                    {
                        <option value="@it.MaDM">@it.tendm</option>
                    }

                </select>
            </div>
        </div>

        <div class="form-group">
            <h3>Nội dung</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.noidung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noidung, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="text" name="matk" value="@Session["acc"]" hidden />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (ViewBag.Message != null)
{
    <script>
    alert("@ViewBag.Message");
    </script>
}
@if (TempData["thongbaoxoa"] != null)
{
    <script>
        alert("@TempData["thongbaoxoa"]");
    </script>
}
<style>
    .video {
        align-items: center;
    }
</style>
<h2>Danh sách phát:</h2>
@foreach (var nn in Session["danhsachvideocuaban"] as List<YOUTUBE.Models.innerjoin>)
{
    <div class="video">
        <a href="" class="smallthumbnail"><img src="@nn.videoo.imagetitle"></a>
        <div class="video-info">
            <h3>@nn.videoo.nametitle</h3>
            <p>@nn.accountt.username</p>
            @*<p>155.235 lượt xem &bull; 2 tuần trước</p>*@
            <p>@nn.videoo.noidung</p>

        </div>
        <div>
            @Html.ActionLink("Edit", "Edit", new { id = nn.videoo.Mavideo })|
            @Html.ActionLink("Delete", "Delete", new { id = nn.videoo.Mavideo })
        </div>
    </div>
}
<script>
    function display(event) {
        document.getElementById("showimg").src = URL.createObjectURL(event.target.files[0]);
    }
    //function display(event2) {
    //    document.getElementById("showimg2").src = URL.createObjectURL(event2.target.files[0]);
    //}
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script>
    var selDiv = "";
    var storedFiles = [];
    $(document).ready(function () {
        $("#imgfile").on("change", handleFileSelect);
        selDiv = $("#selectedBanner");
    });

    function handleFileSelect(e) {
        var files = e.target.files;
        var filesArr = Array.prototype.slice.call(files);
        filesArr.forEach(function (f) {
            if (!f.type.match("image.*")) {
                return;
            }
            storedFiles.push(f);

            var reader = new FileReader();
            reader.onload = function (e) {
                var html =
                    '<img src="' +
                    e.target.result +
                    "\" data-file='" +
                    f.name +
                    "alt='Category Image' height='200px' width='200px'>";
                selDiv.html(html);
            };
            reader.readAsDataURL(f);
        });
    }
</script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>